### ISSUE TITLE
html-style 這個工具怎麽找不到了？

### ISSUE THREAD

**Issue by huge818** [alexayan/html-canvas#1]
html-style 這個工具怎麽找不到了？

**Comment by alexayan** [comment]
供参考：

1. 使用 [postcss](https://github.com/postcss/postcss) 解析 css。
2. 使用 [linkedom](https://github.com/WebReflection/linkedom) 解析 html。
3. 将 1 中的样式应用到 2 中到虚拟 dom 上。
4. 将虚拟 dom 解析为 html。
